### ISSUE TITLE
Can not clone using CocoaPods.

### ISSUE THREAD

**Issue by DarrenBranford** [betfair/aping-ios-sdk#22]
Hi. I have been trying to clone the CocoaPod only to receive the following error:

"warning: Could not find remote branch 2.0 to clone.

fatal: Remote branch 2.0 not found in upstream origin"

Any help or suggestions would be greatly appreciated.

**Comment by seanoshea** [comment]
Hey @DarrenBranford. I tried a fresh project with the following Podfile:

    source 'https://github.com/CocoaPods/Specs.git'
    platform :ios, '5.0'
    pod 'BNGAPI'

and I'm getting very similar results to you:

    sean:TestProject Sean$ pod install --verbose
      Preparing

    Analyzing dependencies

    Updating spec repositories
      $ /usr/bin/git rev-parse  >/dev/null 2>&1
      $ /usr/bin/git rev-parse  >/dev/null 2>&1
    Updating spec repo `master`
      $ /usr/bin/git pull --ff-only
      Already up-to-date.

    Inspecting targets to integrate
      Using `ARCHS` setting to build architectures of target `Pods`: (``)

    Resolving dependencies of `Podfile`
    Starting resolution (2015-03-15 21:19:40 +0000)
    Creating possibility state for BNGAPI (2 remaining)
      Attempting to activate BNGAPI (2.0)
      Activated BNGAPI at BNGAPI (2.0)
      Requiring nested dependencies ()
    Finished resolution (1 steps) (Took 0.001481 seconds) (2015-03-15 21:19:40 +0000)
    Unactivated: 
    Activated: BNGAPI

    Comparing resolved specification to the sandbox manifest
      A BNGAPI

    Downloading dependencies

    -> Installing BNGAPI (2.0)
     > Git download
     > Git download
         $ /usr/bin/git clone https://github.com/betfair/aping-ios-sdk.git     /Users/Sean/Desktop/sean/TestProject/Pods/BNGAPI --single-branch --depth 1
         --branch 2.0
         Cloning into '/Users/Sean/Desktop/sean/TestProject/Pods/BNGAPI'...
         warning: Could not find remote branch 2.0 to clone.
         fatal: Remote branch 2.0 not found in upstream origin
         Unexpected end of command stream

    [!] Error installing BNGAPI
    [!] /usr/bin/git clone https://github.com/betfair/aping-ios-sdk.git     /Users/Sean/Desktop/sean/TestProject/Pods/BNGAPI --single-branch --depth 1 --branch 2.0

    Cloning into '/Users/Sean/Desktop/sean/TestProject/Pods/BNGAPI'...

    warning: Could not find remote branch 2.0 to clone.

Would you mind attaching your Podfile to this bug for reference. Perhaps the project being named `aping-ios-sdk`, but named `BNGAPI` in cocoapods is causing the issue. Will investigate further, but if you have any suggestions, I'm all ears.

**Comment by seanoshea** [comment]
http://guides.cocoapods.org/making/using-pod-lib-create.html could be worth a look. Would mean an overhaul of the current repo structure.

**Comment by seanoshea** [comment]
Asked on SO at http://stackoverflow.com/questions/29076766/cocoapods-could-not-find-remote-branch-to-clone

**Comment by DarrenBranford** [comment]
Thanks for the updates. The Podfile was created as per the instructions in the readme.

    platform :ios, '5.0'
    pod "BNGAPI", "2.0"

I have no previous experience in creating CocoaPods, so I'm not sure that I'll be able to offer any reasonable suggestions.

**Comment by seanoshea** [comment]
Thanks for the info @DarrenBranford. FWIW, downgrading to cocoa pods 0.33.1 via a `sudo gem install cocoapods --version 0.33.1` command should get you back on track in the short term. Still investigating what changed between 0.33.1 and 0.34 with cocoapods, but this downgrade should allow you to develop for the time being. Will post back as soon as I find a more long term solution.

**Comment by seanoshea** [comment]
Pushed the 2.1 version of the library to cocoapods and it should download ok now. Some debug output that I got from a sample `pod install`:

```
sean:TestProject Sean$ pod install --verbose
Preparing

Analyzing dependencies

Updating spec repositories
  $ /usr/bin/git rev-parse  >/dev/null 2>&1
  $ /usr/bin/git rev-parse  >/dev/null 2>&1
Updating spec repo `master`
  $ /usr/bin/git pull --ff-only
  From https://github.com/CocoaPods/Specs
     b4943bb..9a089ca  master     -> origin/master
  Updating b4943bb..9a089ca
  Fast-forward
   Specs/BNGAPI/2.1/BNGAPI.podspec.json | 28 ++++++++++++++++++++++++++++
   1 file changed, 28 insertions(+)
   create mode 100644 Specs/BNGAPI/2.1/BNGAPI.podspec.json

Inspecting targets to integrate
  Using `ARCHS` setting to build architectures of target `Pods`: (``)

Resolving dependencies of `Podfile`
Starting resolution (2015-03-17 20:15:39 +0000)
Creating possibility state for BNGAPI (~> 2.1) (1 remaining)
  Attempting to activate BNGAPI (2.1)
  Activated BNGAPI at BNGAPI (2.1)
  Requiring nested dependencies ()
Finished resolution (1 steps) (Took 0.002576 seconds) (2015-03-17 20:15:39 +0000)
Unactivated: 
Activated: BNGAPI

Comparing resolved specification to the sandbox manifest
  A BNGAPI

Downloading dependencies

-> Installing BNGAPI (2.1)
 > Git download
 > Git download
     $ /usr/bin/git clone https://github.com/betfair/aping-ios-sdk.git     /Users/Sean/Desktop/sean/TestProject/Pods/BNGAPI --single-branch --depth 1
 --branch tags/2.1
     Cloning into '/Users/Sean/Desktop/sean/TestProject/Pods/BNGAPI'...
     Note: checking out 'e4d6294ad613f7c75229498f4eb686292aa585b2'.

     You are in 'detached HEAD' state. You can look around, make experimental
     changes and commit them, and you can discard any commits you make in this
     state without impacting any branches by performing another checkout.

     If you want to create a new branch to retain commits you create, you may
     do so (now or later) by using -b with the checkout command again. Example:

       git checkout -b new_branch_name

  - Running pre install hooks

Generating Pods project
  - Creating Pods project
  - Adding source files to Pods project
  - Adding frameworks to Pods project
  - Adding libraries to Pods project
  - Adding resources to Pods project
  - Linking headers
  - Installing targets
    - Installing target `Pods-BNGAPI` iOS 7.0
    - Installing target `Pods` iOS 7.0
  - Running post install hooks
  - Writing Xcode project file to `Pods/Pods.xcodeproj`
  - Writing Lockfile in `Podfile.lock`
  - Writing Manifest in `Pods/Manifest.lock`

Integrating client project

[!] Please close any current Xcode sessions and use `TestProject.xcworkspace` for this project from now on.

Integrating target `Pods` (`TestProject.xcodeproj` project)
  - Removing (Pods/Pods.xcconfig)
sean:TestProject Sean$
```

Can you try updating your Podfile to look like:

```
source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '5.0'
pod 'BNGAPI', '2.1' 
```

... and see whether that works for you. If it doesn't work, please feel free to get back to me on Github Issues on this repo and I'll do my best to help.

Thanks for taking the time @DarrenBranford to report the issue - much appreciated,

Sean

**Comment by seanoshea** [comment]
Closing this as #25 suggests that the cocoa pod is now fixed.
